### ISSUE TITLE
New Released ESD-ToolKit, RenameISOs, Windows Setup toolkit 4.0.0.0 Beta 1.2

### ISSUE THREAD

**Issue by DineshLohar** [gus33000/ESD-Decrypter#9]
Released ESD-ToolKit, RenameISOs, Windows Setup toolkit 4.0.0.0 Beta 1.2 does not convert new readstone build 14271

**Comment by gus33000** [comment]
Is that when using the ESDDecrypter.bat tool? Next update should fix the launch issue.

**Comment by danielsteiner** [comment]
Can't confirm that. Both, the GUI and the CLI version worked like a charm for me for build 71 and 79. Only the ISO labels are still broken and output ESD-ISO for me.

**Comment by gus33000** [comment]
I just converted an enterprise esd just now and it has the correct label. Is that when combining Core and Pro?

**Comment by gus33000** [comment]
if it's when combining core and pro can you try reversing the order for the esds? I think I messed up the order, it may work when selecting core first and pro second, but it should be reversed to be like an original iso.

**Comment by danielsteiner** [comment]
Yeah it was with pro & core. Will try that after a clean reinstall in case my notebook finally allows me to boot from my flash drive.
